events page: completed upcoming events section ui
she-code-africa/SCA-WEBSITE-V3 pull request #60
Opened 2023-05-13 08:57 UTC by daluclemas

@Lezette , please review.

2023-05-22 19:17 UTC, Lezette requested changes

2023-05-22 19:17 UTC, Lezette commented on src/utils/index.js
Remove the pastEvent and partners array

2023-05-22 19:17 UTC, Lezette commented on src/pages/Events/index.jsx
>  import * as eventpagecomponents from "../../components/Events";
just do import Event from "../../components/Event" instead

2023-05-22 19:17 UTC, Lezette commented on src/components/Events/index.jsx
> +export { default as UpcomingEvents } from "./UpcomingEvents";
This is not necessary, just move all the content in the UpcomingEvents.jsx file into the index file and import it

2023-05-22 19:17 UTC, Lezette commented on src/components/Events/UpcomingEvents.jsx
> +    <div className="w-full flex flex-col-reverse mb-10">
why are you using flex-col-reverse?

2023-05-22 19:17 UTC, Lezette commented on src/components/Events/UpcomingEvents.jsx
object-contain is perfect but why did you use `flex-col-reverse` instead of just placing the items in the correct order?

2023-05-22 19:17 UTC, Lezette commented on src/pages/Events/index.jsx
> +          <figure className="m-0 p-0 w-90 max-w-[1240px] mx-auto h-[520px] overflow-hidden rounded-[50px] border-[18px] border-primary-main-pink mt-36 mb-32">
remove the border for now

2023-05-24 07:01 UTC, daluclemas commented
@Lezette , please review. changes implemented

2023-05-29 11:55 UTC, Lezette requested changes

2023-05-29 11:55 UTC, Lezette commented on src/pages/Events/index.jsx
> +            Upcoming
This should be "Upcoming events" not just Upcoming

2023-05-29 11:55 UTC, Lezette commented on src/pages/Events/index.jsx
> +          {!isLoading && isSuccess && isFetched && (
check for `isFetched && isSuccess` remove` !isLoading` when `isFetched` then `isLoading` becomes false so this is redundant

2023-05-29 11:55 UTC, Lezette commented on src/pages/Events/index.jsx
> +          {!isLoading && isSuccess && isFetched && (
Same comment above

2023-05-29 11:55 UTC, Lezette commented on src/pages/Events/index.jsx
> +  if (isError) {
Add the loading component

2023-05-29 18:08 UTC, Lezette requested changes
Great job just one last thing

2023-05-29 18:08 UTC, Lezette commented on src/pages/Events/index.jsx
> +    return <components.Loading />;
revert this please and I only mentioned that you should add a loading component.

2023-05-29 18:08 UTC, Lezette requested changes
Great job just one last thing

2023-05-30 09:08 UTC, Lezette approved these changes

2023-05-30 09:08 UTC, merged